---
# Ansible Galaxy collection requirements for LabOps
# Usage: ansible-galaxy collection install -r requirements.yml

collections:
  # Used for mail module in send_notification.yaml
  - name: community.general
    version: ">=7.0.0"
    
  # Used for docker_compose_v2 and docker_prune in update_docker.yaml
  - name: community.docker
    version: ">=3.6.0"
    
  # Contains various network and service modules
  - name: ansible.posix
    version: ">=1.5.0"
    
  # Contains windows-related modules (for windows hosts in inventory)
  - name: ansible.windows
    version: ">=1.14.0"