---
# Ubuntu Linux hosts
ubuntu:
  hosts:
    seraph:
      ansible_host: 100.76.155.100
    orac:
      ansible_host: 100.111.153.113
    jarvis:
      ansible_host: 100.90.148.27
    valis:
      ansible_host: 100.124.86.39
      ansible_user: root